version: '3'
services:
  headlamp:
    image: ghcr.io/headlamp-k8s/headlamp:v0.19.1
    command: ["--kubeconfig","/headlamp/config/config", "--port","64446"]
    restart: unless-stopped
    volumes:
      - ~/.kube/:/headlamp/config:ro
    ports:
      - 64446:64446
